# Generated by Django 4.2.7 on 2023-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_allergen_product_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="allergens",
        ),
        migrations.AddField(
            model_name="product",
            name="allergens_text",
            field=models.CharField(
                blank=True,
                help_text="Enter allergens separated by commas",
                max_length=255,
            ),
        ),
    ]
