# Generated by Django 4.2.5 on 2023-11-19 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vouchers", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=250)),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Euro Order Total",
                    ),
                ),
                (
                    "emailAddress",
                    models.EmailField(
                        blank=True, max_length=250, verbose_name="Email Address"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "billingName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingPostcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "billingCountry",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "shippingName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingPostcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "shippingCountry",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "db_table": "Order",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Euro Price"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "db_table": "OrderItem",
            },
        ),
    ]
