# Generated by Django 4.2.5 on 2023-11-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=250)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Euro Order Total"
                    ),
                ),
                (
                    "emailAddress",
                    models.EmailField(
                        blank=True, max_length=250, verbose_name="Email Address"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "billingName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "billingPostcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "billingCountry",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "shippingName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingAddress1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "shippingPostcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "shippingCountry",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Order",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=250)),
                ("quantity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Euro Price"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "db_table": "OrderItem",
            },
        ),
    ]
